config/routes.rb
Rails.application.routes.draw do

    

    resources :products

end

app/models/product.rb
class Product < ActiveRecord::Base

	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  	@products= Product.all
  end

  def new
  	@product= Product.new
  	
  end


  def create

  	@product= Product.new(product_params)
  	if @product.save
  		redirect_to products_path, notice: "El producto fue publicado con exito"
	else
		render :new
	end
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path, notice: "El producto ha sido modificado con éxito"
    else
      render :edit   
    end
  end


  private
  def product_params
  	params.require(:product).permit(:name, :url, :description)  	
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper

	def form_title
		@product.new_record? ? "Publicar" : "Modificar Producto"		
	end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hunt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:notice] %>
  <div class="alert alert-info"><%= flash[:notice] %></div>
<% end %>
<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3"></div>

		<h1><%= form_title %></h1>
			<%= form_for @product do |f| %>
			<div class="form-group">				
				<%= f.text_field :name, class: "form-control input-lg", placeholder: "Ingresa el nombre del producto"  %>				
			</div>

			<div class="form-group">				
				<%= f.text_field :url, class: "form-control input-lg", placeholder: "Ingresa la URL del producto"  %>				
			</div>

			<div class="form-group">				
				<%= f.text_area :description, class: "form-control input-lg", placeholder: "Ingresa la descripción del producto"  %>				
			</div>
			<div>
	          <%= f.submit form_title , class: "btn btn-primary btn-lg btn-block" %>
	        </div>
        <% end %>

	</div>
</div>

app/views/products/edit.html.erb
<%= render 'form' %>

app/views/products/index.html.erb
	<div class="container">
		<div class="row">
			<div class="col-sm-12">
				<h1>Productos</h1>				
				<div class="text-right">
				  <%= link_to "Publicar Producto", new_product_path, class: "btn btn-primary" %>
				</div>
				<table class="table">
					<tr>
						<th>Id</th>
						<th>Nombre</th>
						<th>URL</th>
						<th>Description</th>
					</tr>
					<% @products.each do |product| %>
					<tr>
						<td> <%= product.id %> </td>
						<td><%= link_to product.name, product %></td>
						<td> <%= product.url %></td>
						<td> <%= product.description %></td>
						<td><%= link_to "Editar", edit_product_path(product) %></td>
					</tr>
					<% end %>
				</table>
			</div>
		</div>
	</div>

app/views/products/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3"></div>

		<h1>Publicar productos</h1>
			<%= form_for @product do |f| %>
			<div class="form-group">				
				<%= f.text_field :name, class: "form-control input-lg", placeholder: "Ingresa el nombre del producto"  %>				
			</div>

			<div class="form-group">				
				<%= f.text_field :url, class: "form-control input-lg", placeholder: "Ingresa la URL del producto"  %>				
			</div>

			<div class="form-group">				
				<%= f.text_area :description, class: "form-control input-lg", placeholder: "Ingresa la descripción del producto"  %>				
			</div>
			<div>
	          <%= f.submit "Publicar Producto", class: "btn btn-primary btn-lg btn-block" %>
	        </div>
        <% end %> 




	</div>
</div>

app/views/products/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<h1><%= @product.name %></h1>
		    <p><%= @product.description %></p>
		    <a href="<%= @product.url %>" target="_blank">¡Obtenlo!</a>
		</div>
	</div>
</div>